# Generated by Django 5.2.8 on 2025-11-13 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfdocument',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
